### ISSUE TITLE
Do you have any plans to release a human-labeled dataset? If so, when would that be?

### ISSUE THREAD

**Issue by yachenkang** [csmile-1006/PreferenceTransformer#1]
The problem that the paper addresses is very interesting, with the surprising difference in performance between human-labeled and synthetic data being particularly noteworthy. The release of a human-labeled dataset would undoubtedly have a significant impact on the advancement of research in this field, and I am eagerly looking forward to it.

**Comment by csmile-1006** [comment]
Hi! Thank you for your interest in our project.
We release the real human preference in the latest commit.
Please check and feel free to ask if you have any further questions.

Many Thanks,
Changyeon Kim
https://changyeon.page
