### ISSUE TITLE
can I get some other indices for my human label ?

### ISSUE THREAD

**Issue by liovn** [csmile-1006/PreferenceTransformer#2]
Thank you for your wonderful work. Besides generating `human_label` with the collected `indices` in your file, can I collect more `indices` or my own indices?  hope you give some useful suggestions

**Comment by csmile-1006** [comment]
Hello, thank you for your interest.
You could make your own `indices` by learning reward model with different `base_path`.
Please follow the code here: 
https://github.com/csmile-1006/PreferenceTransformer/blob/8b34c6979fd08522cd28a3e5d7ffac132f341790/JaxPref/new_preference_reward_main.py#L156
