### ISSUE TITLE
Question about 'reverse'

### ISSUE THREAD

**Issue by mrqy0610** [csmile-1006/PreferenceTransformer#5]
Hello, thanks for your great work. I have a question about the parameter “reverse”, in your code if "reverse" is set to be True, the data sequence    will be (s, a, s, a, …), otherwise it will be (a, s, a, s, ……). And in your code you choose the later, I wonder is there any reason why you choose to put action before state? In your paper, it seems that the data sequence should be  (s, a, s, a, …).
<img width="367" alt="2a5421f741bd6d7d7edefe152b67ec3" src="https://github.com/csmile-1006/PreferenceTransformer/assets/59873206/02855083-de7b-4dc1-89b6-27b2722b43a2">

**Comment by csmile-1006** [comment]
Hello! Thanks for your question.
For that part, it is just implementation detail for better performance. In consise, the sequence should be (s,a), so you could use the reverse argument as True. It's same that we consume same sequence as an input.

Thank you for your questions.
